version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - mongo
    links:
      - mongo