name: .NET Core Web API Deployment

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        docker-compose build
        docker-compose run web dotnet test
        
    - name: Deploy to Elastic Beanstalk
      run: eb deploy
